#ifndef __OBJECT_TRACKING_H
#define __OBJECT_TRACKING_H

#define USE_CALIBRATED_SETTING 1
#define USE_MORPHOLOGICAL_FILTER 1
#define ENABLE_OBJECT_TRACKING 1

#define FINE_CALIBRATED_H_MIN 0
#define FINE_CALIBRATED_H_MAX 256
#define FINE_CALIBRATED_S_MIN 0
#define FINE_CALIBRATED_S_MAX 256
#define FINE_CALIBRATED_V_MIN 0
#define FINE_CALIBRATED_V_MAX 256

#endif
